# Разведочный анализ

In [3]:
import pandas as pd


df = pd.read_csv("/Users/ayaansavvinov/Downloads/НЃҐ†п ѓ†ѓ™† 2/delivery_investigation.csv")
print(df.shape)
display(df.nunique())
print(df.duplicated().sum()) # полных повторов
print(df.isna().sum())
display(df.info())
print(df.select_dtypes(include='number').columns)

(1278, 17)

order_id            1200
created_at          1162
updated_at          1260
district              27
restaurant            24
source_system          4
transport             11
weather                3
distance_km          687
prep_minutes         227
courier_load           4
delivery_minutes     504
promised_minutes      55
order_sum            262
status                 8
rating                 7
courier_id           152
dtype: int64

10
order_id              0
created_at            0
updated_at            0
district              0
restaurant            0
source_system         0
transport             0
weather               0
distance_km           0
prep_minutes         53
courier_load          0
delivery_minutes     60
promised_minutes      0
order_sum             0
status                0
rating              459
courier_id          100
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 1278 entries, 0 to 1277
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1278 non-null   str
 1   created_at        1278 non-null   str
 2   updated_at        1278 non-null   str
 3   district          1278 non-null   str
 4   restaurant        1278 non-null   str
 5   source_system     1278 non-null   str
 6   transport         1278 non-null   str
 7   weather           1278 non-null   str
 8   distance_km       1278 non-null   str
 9   prep_minutes      1225 non-null   float64
 10  courier_load      1278 non-null   int64
 11  delivery_minutes  1218 non-null   float64
 12  promised_minutes  1278 non-null   int64
 13  order_sum         1278 non-null   str
 14  status            1278 non-null   str
 15  rating            819 non-null    float64
 16  courier_id        1178 non-null   str
dtypes: float64(3), int64(2), str(12)
memory usage: 169.9 KB

None

Index(['prep_minutes', 'courier_load', 'delivery_minutes', 'promised_minutes',
       'rating'],
      dtype='str')

In [4]:
display(df["order_id"].value_counts())
display(df["district"].value_counts())
display(df["restaurant"].value_counts())
display(df["order_sum"].value_counts())
display(df["courier_id"].value_counts())

order_id
D100819    3
D100015    2
D100028    2
D100029    2
D100042    2
          ..
D101196    1
D101197    1
D101198    1
D101199    1
D101200    1
Name: count, Length: 1200, dtype: int64

district
Центр       338
Юг          269
Север       212
Восток      206
Запад       200
север         4
Запад         4
ЮГ            4
 север        4
центр         3
запад         3
Центр         3
Восток        3
Север         3
ВОСТОК        3
ЦЕНТР         3
Север         2
Запад         2
юг            2
Юг            2
 запад        2
Центр         1
Юг            1
Восток        1
СЕВЕР         1
 юг           1
 восток       1
Name: count, dtype: int64

restaurant
Пицца & Ко           177
Зелёная кухня        168
Wok Station          157
Пекарня №7           155
Taco Point           153
Хинкали House        152
Бургерная 24         138
Sushi Lab            133
 пекарня №7            9
SUSHI LAB              5
ПИЦЦА & КО             4
ЗЕЛЁНАЯ КУХНЯ          4
 зелёная кухня         4
ПЕКАРНЯ №7             2
 sushi lab             2
 бургерная 24          2
 taco point            2
 wok station           2
WOK STATION            2
 пицца & ко            2
 хинкали house         2
БУРГЕРНАЯ 24           1
TACO POINT             1
  зелёная кухня        1
Name: count, dtype: int64

order_sum
820        19
850        16
1020       16
1140       16
720        16
           ..
2960        1
1970        1
2 590 ₽     1
2930        1
2720        1
Name: count, Length: 262, dtype: int64

courier_id
C023    17
C132    14
C075    14
C062    13
C043    13
        ..
C087     3
C072     2
C117     2
C042     2
C143     1
Name: count, Length: 152, dtype: int64

In [5]:
display(df.describe())
display(df["order_id"].duplicated().sum())
display(df["order_id"].value_counts())

,prep_minutes,courier_load,delivery_minutes,promised_minutes,rating
count,1225.000000,1278.000000,1218.000000,1278.000000,819.000000
mean,16.421143,1.878717,88.047783,45.095462,4.540904
std,5.042329,0.879685,349.832834,10.350262,0.616976
min,-17.600000,1.000000,-32.800000,35.000000,0.000000
25%,13.400000,1.000000,26.500000,36.000000,4.000000
50%,16.500000,2.000000,35.500000,43.000000,5.000000
75%,19.600000,2.000000,46.575000,50.000000,5.000000
max,32.100000,4.000000,3588.000000,96.000000,9.000000

np.int64(78)

order_id
D100819    3
D100015    2
D100028    2
D100029    2
D100042    2
          ..
D101196    1
D101197    1
D101198    1
D101199    1
D101200    1
Name: count, Length: 1200, dtype: int64

# Предобработка

In [ ]:
df_clean = df.copy()
df_clean['distance_km'] = df_clean['distance_km'].astype(str).str.replace(',', '.')
df_clean['order_sum'] = df_clean['order_sum'].astype(str).str.replace(',', '.')
df_clean['order_sum'] = df_clean['order_sum'].astype(str).str.replace('₽', '')
df_clean['order_sum'] = df_clean['order_sum'].astype(str).str.replace(' ', '')
df_clean = df_clean.drop_duplicates(subset=['order_id'], keep='first')
df_clean.loc[df_clean['prep_minutes'] < 0, 'prep_minutes'] = None
df_clean.loc[df_clean['delivery_minutes'] < 0, 'delivery_minutes'] = None
df_clean['distance_km'] = df_clean['distance_km'].astype('float64')
df_clean['order_sum'] = df_clean['order_sum'].astype('float64')
df_clean.loc[df_clean['distance_km'] < 0, 'distance_km'] = None

# Повторный анализ данных

In [ ]:
print(df_clean.shape)
display(df_clean.nunique())
print(df_clean.duplicated().sum())
print(df_clean.isna().sum())
display(df_clean.info())
print(df_clean.select_dtypes(include='number').columns)

(1200, 17)

order_id            1200
created_at          1162
updated_at          1200
district              23
restaurant            23
source_system          4
transport             10
weather                3
distance_km          674
prep_minutes         225
courier_load           4
delivery_minutes     501
promised_minutes      55
order_sum            235
status                 6
rating                 7
courier_id           152
dtype: int64

0
order_id              0
created_at            0
updated_at            0
district              0
restaurant            0
source_system         0
transport             0
weather               0
distance_km           0
prep_minutes         50
courier_load          0
delivery_minutes      0
promised_minutes      0
order_sum             0
status                0
rating              395
courier_id           93
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1200 non-null   str
 1   created_at        1200 non-null   str
 2   updated_at        1200 non-null   str
 3   district          1200 non-null   str
 4   restaurant        1200 non-null   str
 5   source_system     1200 non-null   str
 6   transport         1200 non-null   str
 7   weather           1200 non-null   str
 8   distance_km       1200 non-null   float64
 9   prep_minutes      1150 non-null   float64
 10  courier_load      1200 non-null   int64
 11  delivery_minutes  1200 non-null   float64
 12  promised_minutes  1200 non-null   int64
 13  order_sum         1200 non-null   float64
 14  status            1200 non-null   str
 15  rating            805 non-null    float64
 16  courier_id        1107 non-null   str
dtypes: float64(5), int64(2), str(10)
memory usage: 159.5 KB

None

Index(['distance_km', 'prep_minutes', 'courier_load', 'delivery_minutes',
       'promised_minutes', 'order_sum', 'rating'],
      dtype='str')

In [8]:
display(df_clean["order_id"].value_counts())
display(df_clean["district"].value_counts())
display(df_clean["restaurant"].value_counts())
display(df_clean["order_sum"].value_counts())
display(df_clean["courier_id"].value_counts())

order_id
D100001    1
D100002    1
D100003    1
D100004    1
D100005    1
          ..
D101196    1
D101197    1
D101198    1
D101199    1
D101200    1
Name: count, Length: 1200, dtype: int64

district
Центр      317
Юг         256
Север      202
Запад      190
Восток     190
север        4
Запад        4
ЮГ           4
центр        3
запад        3
Центр        3
Восток       3
Север        3
ВОСТОК       3
ЦЕНТР        3
Север        2
Запад        2
юг           2
Юг           2
Центр        1
Юг           1
Восток       1
СЕВЕР        1
Name: count, dtype: int64

restaurant
Пицца & Ко         173
Зелёная кухня      157
Хинкали House      146
Пекарня №7         145
Taco Point         144
Wok Station        142
Бургерная 24       134
Sushi Lab          123
 пекарня №7          7
ПИЦЦА & КО           4
ЗЕЛЁНАЯ КУХНЯ        4
SUSHI LAB            4
 зелёная кухня       3
ПЕКАРНЯ №7           2
 sushi lab           2
 бургерная 24        2
WOK STATION          2
БУРГЕРНАЯ 24         1
 taco point          1
 wok station         1
 пицца & ко          1
TACO POINT           1
 хинкали house       1
Name: count, dtype: int64

order_sum
860.0     17
1140.0    16
750.0     15
850.0     15
820.0     15
          ..
1970.0     1
320.0      1
2590.0     1
2930.0     1
2720.0     1
Name: count, Length: 235, dtype: int64

courier_id
C023    16
C043    13
C098    13
C064    13
C075    13
        ..
C087     3
C072     2
C117     2
C042     2
C143     1
Name: count, Length: 152, dtype: int64

In [9]:
display(df_clean.describe())
display(df_clean["order_id"].duplicated().sum())

,distance_km,prep_minutes,courier_load,delivery_minutes,promised_minutes,order_sum,rating
count,1200.000000,1150.000000,1200.000000,1200.000000,1200.000000,1200.000000,805.000000
mean,91.631608,16.440435,1.877500,86.558417,45.118333,1200.725000,4.542857
std,688.587767,4.930175,0.884013,342.932061,10.403903,567.218216,0.618709
min,-3.090000,0.000000,1.000000,0.000000,35.000000,220.000000,0.000000
25%,1.940000,13.300000,1.000000,26.400000,36.000000,800.000000,4.000000
50%,3.605000,16.500000,2.000000,35.500000,43.000000,1090.000000,5.000000
75%,5.835000,19.600000,2.000000,46.600000,50.000000,1460.000000,5.000000
max,12090.000000,32.100000,4.000000,3588.000000,96.000000,4660.000000,9.000000

np.int64(0)

Главный вопрос опоздания

In [ ]:
df_clean['is_late'] = df_clean['delivery_minutes'] > df_clean['promised_minutes']
d = df_clean[df_clean['status'] == 'delivered']

display(d.groupby('district')['is_late'].mean())
display(d.groupby('transport')['delivery_minutes'].agg(['mean','median']))
display(d.groupby('weather')['is_late'].mean())
display(d.groupby('courier_load')['is_late'].mean())

district
ВОСТОК     0.000000
Восток     0.234286
Восток     0.000000
Восток     0.000000
Запад      0.211111
Запад      0.000000
Запад      0.000000
СЕВЕР      0.000000
Север      0.218579
Север      0.000000
Север      0.333333
ЦЕНТР      0.000000
Центр      0.218430
Центр      0.000000
Центр      0.000000
ЮГ         0.250000
Юг         0.477064
Юг         1.000000
Юг         0.500000
запад      0.000000
север      0.000000
центр      0.333333
юг         0.500000
Name: is_late, dtype: float64

                 mean  median
transport
 bike       50.800000   46.70
 car        32.200000   29.80
 scooter    35.525000   34.95
BIKE        24.371429   23.40
CAR         31.833333   23.60
SCOOTER     70.000000   70.00
bike        39.777003   37.20
car         34.797348   32.85
scooter    228.473651   38.30
walk        58.136000   49.55

weather
clear    0.224409
rain     0.269565
snow     0.612245
Name: is_late, dtype: float64

courier_load
1    0.211454
2    0.284974
3    0.308081
4    0.500000
Name: is_late, dtype: float64

До и После

In [ ]:
comparison = pd.DataFrame({
    'ДО':    [df.shape[0], df['order_id'].nunique(), df.duplicated().sum(),
              round(df['delivery_minutes'].mean(),2),
              round(df['delivery_minutes'].median(),2)],
    'ПОСЛЕ': [df_clean.shape[0], df_clean['order_id'].nunique(), df_clean.duplicated().sum(),
              round(df_clean['delivery_minutes'].mean(),2),
              round(df_clean['delivery_minutes'].median(),2)]
}, index=['Строк','Уникальных order_id','Повторов','Среднее delivery','Медиана delivery'])
display(comparison)

                          ДО    ПОСЛЕ
Строк                1278.00  1200.00
Уникальных order_id  1200.00  1200.00
Повторов               10.00     0.00
Среднее delivery       88.05    86.56
Медиана delivery       35.50    35.50